import { Command } from "../types/commands";

export const commands: Command[] = [
  {
    name: "about",
    description: "Shows information about me",
    output: [
      "╔════════════════════════════════════════════════════════╗",
      "║              SUMAN BISUNKHE - DEVELOPER                ║",
      "╚════════════════════════════════════════════════════════╝",
      "",
      "👨‍💻 Full Stack Developer & Java Enthusiast",
      "🚀 Builder of RoomRadar & XpertLink",
      "💡 Passionate about creating innovative systems",
      "🎯 Focus: Building scalable web applications",
      "",
      "Type 'skills' to see my technical expertise",
      "Type 'projects' to view my work",
    ],
  },
  {
    name: "skills",
    description: "List of my technical skills",
    output: [
      "╔════════════════════════════════════════════════════════╗",
      "║                   TECHNICAL SKILLS                     ║",
      "╚════════════════════════════════════════════════════════╝",
      "",
      "Backend:",
      "  ▸ Java              ████████████████████ 90%",
      "  ▸ Spring Boot       ████████████████░░░░ 80%",
      "  ▸ SQL/Database      ███████████████░░░░░ 75%",
      "",
      "Frontend:",
      "  ▸ React.js          ████████████░░░░░░░░ 60%",
      "  ▸ Next.js           ████████████░░░░░░░░ 60%",
      "  ▸ TypeScript        ███████████░░░░░░░░░ 55%",
      "",
      "Tools & Others:",
      "  ▸ Git/GitHub        ████████████████░░░░ 80%",
      "  ▸ Docker            ██████████░░░░░░░░░░ 50%",
      "  ▸ REST APIs         ███████████████████░ 85%",
    ],
  },
  {
    name: "projects",
    description: "List of my projects",
    output: [
      "╔════════════════════════════════════════════════════════╗",
      "║                      PROJECTS                          ║",
      "╚════════════════════════════════════════════════════════╝",
      "",
      "🏠 RoomRadar",
      "   Real-time room rental platform with advanced search",
      "   Tech: Java, Spring Boot, React",
      "   Status: Live",
      "",
      "🤝 XpertLink",
      "   Expert consultation hub connecting professionals",
      "   Tech: Java, Spring Boot, Next.js",
      "   Status: In Development",
      "",
      "✅ PrioritizeMe",
      "   Smart task management system with AI insights",
      "   Tech: Java, React, PostgreSQL",
      "   Status: Beta",
      "",
      "Type 'contact' to get in touch about projects",
    ],
  },
  {
    name: "contact",
    description: "Shows how to contact me",
    output: [
      "╔════════════════════════════════════════════════════════╗",
      "║                    GET IN TOUCH                        ║",
      "╚════════════════════════════════════════════════════════╝",
      "",
      "📧 Email:     suman@example.com",
      "💼 LinkedIn:  linkedin.com/in/suman",
      "🐙 GitHub:    github.com/suman",
      "🐦 Twitter:   @suman_dev",
      "",
      "💬 I'm open to:",
      "   • Freelance opportunities",
      "   • Collaboration on open-source",
      "   • Technical discussions",
      "   • Coffee chats about tech ☕",
    ],
  },
  {
    name: "help",
    description: "Shows available commands",
    output: [
      "╔════════════════════════════════════════════════════════╗",
      "║                 AVAILABLE COMMANDS                     ║",
      "╚════════════════════════════════════════════════════════╝",
      "",
      "  about      →  Learn about me",
      "  skills     →  View my technical skills",
      "  projects   →  Explore my projects",
      "  contact    →  Get my contact information",
      "  clear      →  Clear the terminal",
      "  help       →  Show this message",
      "",
      "💡 Tip: Just start typing and press Enter!",
    ],
  },
  {
    name: "clear",
    description: "Clears the terminal",
    output: [],
  },
];
